"""Tests for the .gcode.3mf extraction + SD-card helpers.

We synthesise an OrcaSlicer-style archive so the critical extraction path is
fully covered without needing the OrcaSlicer binary installed.
"""

from __future__ import annotations

import zipfile
from pathlib import Path

import pytest

from slicer.extract import extract_gcode, list_plate_gcode, read_slice_info, summarize
from slicer.sdcard import copy_to_sd, sanitize_name

GCODE = b"; generated by test\nG28\nG1 Z5 F5000\nM104 S240\n"

SLICE_INFO = b"""<?xml version="1.0" encoding="UTF-8"?>
<config>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="prediction" value="3360"/>
    <metadata key="weight" value="12.34"/>
    <filament id="1" type="PETG" used_m="1.23" used_g="3.45"/>
  </plate>
</config>
"""


@pytest.fixture
def archive(tmp_path: Path) -> Path:
    path = tmp_path / "fridge_drawer.gcode.3mf"
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", GCODE)
        zf.writestr("Metadata/slice_info.config", SLICE_INFO)
        zf.writestr("3D/3dmodel.model", b"<model/>")  # noise
    return path


def test_list_plate_gcode(archive: Path) -> None:
    assert list_plate_gcode(archive) == {1: "Metadata/plate_1.gcode"}


def test_extract_gcode_default_name(archive: Path) -> None:
    out = extract_gcode(archive)
    # foo.gcode.3mf -> foo.gcode (not foo.gcode.gcode)
    assert out.name == "fridge_drawer.gcode"
    assert out.read_bytes() == GCODE


def test_extract_missing_plate_raises(archive: Path) -> None:
    with pytest.raises(FileNotFoundError):
        extract_gcode(archive, plate=7)


def test_read_slice_info(archive: Path) -> None:
    plates = read_slice_info(archive)
    assert len(plates) == 1
    plate = plates[0]
    assert plate.index == 1
    assert plate.print_time_s == 3360.0
    assert plate.weight_g == 12.34
    assert plate.filaments[0]["type"] == "PETG"


def test_summarize(archive: Path) -> None:
    summary = summarize(archive)
    assert summary["plates"][0]["print_time_s"] == 3360.0


def test_summarize_no_info(tmp_path: Path) -> None:
    path = tmp_path / "bare.gcode.3mf"
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("Metadata/plate_1.gcode", GCODE)
    assert summarize(path)["plates"] == []


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        ("fridge drawer v3", "FRIDGE_D.gcode"),
        ("heater-mount", "HEATER_M.gcode"),
        ("", "PART.gcode"),
        ("0123456789", "01234567.gcode"),
    ],
)
def test_sanitize_name(raw: str, expected: str) -> None:
    assert sanitize_name(raw) == expected


def test_copy_to_sd(tmp_path: Path) -> None:
    src = tmp_path / "out.gcode"
    src.write_bytes(GCODE)
    sd = tmp_path / "sd"
    sd.mkdir()
    dest = copy_to_sd(src, sd, name="fridge drawer")
    assert dest == sd / "FRIDGE_D.gcode"
    assert dest.read_bytes() == GCODE
